project_id = "arfzuyonatmkcngnnedc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://arfzuyonatmkcngnnedc.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = true
enable_email_confirmations = false
enable_email_change_confirmations = false
enable_phone_confirmations = false
enable_phone_change_confirmations = false
disable_signup = false
external_anonymous_users_enabled = true
auto_confirm_email = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_email_change_enabled = true
enable_reauthentication = true

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."
max_frequency = 5

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.send-reminder-email]
verify_jwt = false