// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arfzuyonatmkcngnnedc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZnp1eW9uYXRta2NuZ25uZWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTMwODMsImV4cCI6MjA2ODY2OTA4M30.Cztn-yFeOpJTrDi1ezuXpiEapRXyj39WDCtonwXEw4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});